import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Footer, Header, Sidebar } from "@/sections";
// import cn from "classnames";
// import { API } from "./api";

const notoSans = Noto_Sans({ subsets: ["latin"], weight: ["300", "400", "500", "700"], display: "swap" });

export const metadata: Metadata = {
  title: "Top App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // params,
{
  children: React.ReactNode;
  // params: {
  //   type: string;
  //   alias: string;
  // };
}) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        {/* <Header /> */}
        <Sidebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// export const withLayout = <T extends Record<string, unknown> & IAppContext>(Component: FunctionComponent<T>) => {
//   return function withLayoutComponent(props: T): JSX.Element {
//     return (
//       <AppContextProvider menu={props.menu} firstCategory={props.firstCategory}>
//         <Layout>
//           <Component {...props} />
//         </Layout>
//       </AppContextProvider>
//     );
//   };
// };
